// Utility kernels shared across the model.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// Element-wise add: a[i] += b[i]. Operates on activation buffers (storage_t).
// Internal arithmetic in float so fp16 storage doesn't lose precision on
// long residual chains (residual stream variance shrinks otherwise).
__kernel void element_add(__global storage_t* a,
                          __global const storage_t* b,
                          const int n) {
    int gid = get_global_id(0);
    if (gid < n) {
        float av = LOAD(a, gid);
        float bv = LOAD(b, gid);
        STORE(a, gid, av + bv);
    }
}

// Per-row split of a row-major [rows, 2*half] tensor into two contiguous
// [rows, half] tensors. Use this for chunk(2, dim=-1) on GLU/SwiGLU/GeGLU
// gate/up activations — byte-offset sub-buffer splits produce wrong data
// because contiguous bytes span BOTH halves of the first few rows, not
// first-half of every row.
//
// global_work_size = rows * half_cols (one work-item per output element of one half)
// Layout:
//   src[row, col]   = input[row * (2*half_cols) + col]              for col in [0, 2*half_cols)
//   first[row, i]   = input[row * (2*half_cols) + i]                for i in [0, half_cols)
//   second[row, i]  = input[row * (2*half_cols) + i + half_cols]    for i in [0, half_cols)
//
// IMPORTANT — DO NOT rename half_cols to bare 'half'. OpenCL's cl_khr_fp16
// makes 'half' a reserved type token (the fp16 storage type defined by the
// LOAD/STORE preamble). Adreno's clang front-end treats any identifier named
// 'half' as a parse error in this context. Keep the suffix.
__kernel void split_last_dim_2(
    __global const storage_t* src,
    __global storage_t* first,
    __global storage_t* second,
    const int rows,
    const int half_cols) {
    int gid = get_global_id(0);
    const int total = rows * half_cols;
    if (gid >= total) return;
    int row = gid / half_cols;
    int col = gid - row * half_cols;
    int src_base = row * (half_cols * 2);
    float a = LOAD(src, src_base + col);
    float b = LOAD(src, src_base + col + half_cols);
    STORE(first,  row * half_cols + col, a);
    STORE(second, row * half_cols + col, b);
}
