// Auto-generated by scaffoldTs.ts -- do not edit manually.
//
// Lazy cos/sin precomputation for rotary embeddings. Caches per
// (head_dim, theta) — most models reuse the same head_dim across all 16-32
// attention layers, so this is a single allocation amortized across the
// entire forward pass. Grows on demand if a later call requests a longer
// max_seq_len than what's cached.
//
// Storage matches the model dtype (fp16/fp32) so the rope kernel sees
// the same storage_t the rest of the pipeline uses.

#include "rotary_tables.h"
#include "opencl_context.h"
#include "utils.h"          // nnopt_storage_t, nnopt_f32_to_f16
#include "debug_utils.h"

#include <cmath>
#include <cstdint>
#include <cstring>
#include <string>
#include <unordered_map>
#include <vector>

namespace {
struct CachedTable {
    cl_mem cos = nullptr;
    cl_mem sin = nullptr;
    int    max_seq_len = 0;
    int    head_dim = 0;
    float  theta = 0.0f;
};

// Keyed by "head_dim:theta_int" so two attention variants with different
// thetas (rare but possible) get separate tables.
static std::unordered_map<std::string, CachedTable> g_cache;

static std::string key_for(int head_dim, float theta) {
    char buf[64];
    // theta_base is typically 10000 or 500000; multiply by 100 to capture
    // any fractional differences in rope_theta values seen in the wild.
    long long theta_int = (long long)std::llround((double)theta * 100.0);
    std::snprintf(buf, sizeof(buf), "%d:%lld", head_dim, theta_int);
    return std::string(buf);
}

static bool build_table(OpenCLContext& cl_ctx,
                         int seq_len,
                         int head_dim,
                         float theta,
                         cl_mem& cos_out,
                         cl_mem& sin_out) {
    const int D = head_dim;
    const int half_dim = D / 2;
    if (D <= 0 || half_dim <= 0) {
        NNOPT_ERROR_FMT("nnopt_get_rotary_tables: invalid head_dim %d", head_dim);
        return false;
    }

    std::vector<float> cos_f((size_t)seq_len * (size_t)D);
    std::vector<float> sin_f((size_t)seq_len * (size_t)D);
    for (int t = 0; t < seq_len; ++t) {
        for (int i = 0; i < half_dim; ++i) {
            const float exponent = (2.0f * (float)i) / (float)D;
            const float inv_freq = std::pow(theta, -exponent);  // SYNC-OK: init path
            const float angle = (float)t * inv_freq;
            const float c = std::cos(angle);
            const float s = std::sin(angle);
            cos_f[(size_t)t * (size_t)D + (size_t)i] = c;
            sin_f[(size_t)t * (size_t)D + (size_t)i] = s;
            cos_f[(size_t)t * (size_t)D + (size_t)i + (size_t)half_dim] = c;
            sin_f[(size_t)t * (size_t)D + (size_t)i + (size_t)half_dim] = s;
        }
    }

    std::vector<nnopt_storage_t> cos_h((size_t)seq_len * (size_t)D);
    std::vector<nnopt_storage_t> sin_h((size_t)seq_len * (size_t)D);
    for (size_t i = 0; i < cos_h.size(); ++i) {
#ifdef NNOPT_USE_FP16
        cos_h[i] = (nnopt_storage_t)nnopt_f32_to_f16(cos_f[i]);
        sin_h[i] = (nnopt_storage_t)nnopt_f32_to_f16(sin_f[i]);
#else
        cos_h[i] = cos_f[i];
        sin_h[i] = sin_f[i];
#endif
    }

    cl_context ctx = cl_ctx.context();
    cl_int err = CL_SUCCESS;
    const size_t bytes = cos_h.size() * sizeof(nnopt_storage_t);

    cl_mem cos_buf = clCreateBuffer(ctx, CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR,
                                    bytes, cos_h.data(), &err);
    if (err != CL_SUCCESS || !cos_buf) {
        NNOPT_ERROR_FMT("nnopt_get_rotary_tables: alloc cos_buf failed: %d", (int)err);
        return false;
    }
    cl_mem sin_buf = clCreateBuffer(ctx, CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR,
                                    bytes, sin_h.data(), &err);
    if (err != CL_SUCCESS || !sin_buf) {
        NNOPT_ERROR_FMT("nnopt_get_rotary_tables: alloc sin_buf failed: %d", (int)err);
        clReleaseMemObject(cos_buf);
        return false;
    }
    cos_out = cos_buf;
    sin_out = sin_buf;
    return true;
}
} // namespace

bool nnopt_get_rotary_tables(OpenCLContext& cl_ctx,
                              int max_seq_len,
                              int head_dim,
                              float theta_base,
                              cl_mem& cos_out,
                              cl_mem& sin_out) {
    if (max_seq_len <= 0 || head_dim <= 0) {
        NNOPT_ERROR_FMT(
            "nnopt_get_rotary_tables: bad args (max_seq_len=%d, head_dim=%d)",
            max_seq_len, head_dim);
        return false;
    }

    const std::string k = key_for(head_dim, theta_base);
    auto it = g_cache.find(k);
    if (it != g_cache.end() && it->second.cos && it->second.sin && it->second.max_seq_len >= max_seq_len) {
        cos_out = it->second.cos;
        sin_out = it->second.sin;
        return true;
    }

    // Need to (re)build. Free old tables for this key; build new ones.
    if (it != g_cache.end()) {
        if (it->second.cos) clReleaseMemObject(it->second.cos);
        if (it->second.sin) clReleaseMemObject(it->second.sin);
        g_cache.erase(it);
    }

    cl_mem cos_buf = nullptr, sin_buf = nullptr;
    if (!build_table(cl_ctx, max_seq_len, head_dim, theta_base, cos_buf, sin_buf)) {
        return false;
    }

    CachedTable t;
    t.cos = cos_buf;
    t.sin = sin_buf;
    t.max_seq_len = max_seq_len;
    t.head_dim = head_dim;
    t.theta = theta_base;
    g_cache[k] = t;

    cos_out = cos_buf;
    sin_out = sin_buf;
    return true;
}
